/**
 * Vocabulary for the Stack Optimizer.
 *
 * The optimizer answers one question — which trusted model is cheapest for a
 * stated monthly workload, given hard requirements — and it answers it the
 * same way every time. Three rules shape every type here.
 *
 *   * Unknown fails closed. A requirement that depends on evidence nobody
 *     published is unsatisfied, never assumed. `supportsVision === null` is
 *     not vision support, and an unobserved context window never clears a
 *     floor.
 *   * Missing pricing never wins. A model with no comparable price is still
 *     reported as eligible when it meets the requirements, but it is not
 *     ranked, cannot be the winner, and its cost stays null rather than zero.
 *   * Every number is reproducible. Each cost component carries the tokens,
 *     the published unit price and the formula that produced it, so a reader
 *     can recompute the ranking by hand.
 *
 * Nothing in this module is generated by a language model. Costs are
 * arithmetic over canonical evidence and ranking is a total order.
 */

import type {
  EvidenceDomain,
  ModelFreshness,
  ModelProviderIdentity,
} from "../explorer/types";
import type { ProvenanceView } from "../product/provenance";
import type { LifecycleState } from "../supabase/types";

/** What the caller is optimizing for. */
export type OptimizationPriority =
  | "lowest_total_cost"
  | "lowest_input_cost"
  | "lowest_output_cost";

/** Monthly token volumes. Both dimensions are required; either may be zero. */
export interface WorkloadSpec {
  monthlyInputTokens: number;
  monthlyOutputTokens: number;
}

export interface StackOptimizerRequest {
  workload: WorkloadSpec;
  /** Inclusive floor. An unobserved context window never clears it. */
  minContextWindow?: number;
  /** Inclusive floor. Unobserved max output tokens never clears it. */
  minMaxOutputTokens?: number;
  /** true keeps only supportsVision === true. false imposes no constraint. */
  visionRequired?: boolean;
  /** true keeps only supportsToolCalling === true. false imposes no constraint. */
  toolCallingRequired?: boolean;
  /** Allowed provider slugs or well-known aliases. Empty means every provider. */
  providers?: readonly string[];
  /** Drops models observed to be deprecated or retired. */
  activeOnly?: boolean;
  excludeModelIds?: readonly string[];
  excludeProviders?: readonly string[];
  priority?: OptimizationPriority;
  /** Ceiling on ranked rows returned. Excluded rows are always complete. */
  limit?: number;
  /** Prices in another currency are not converted; they are not comparable. */
  currency?: string;
}

/** The request after defaults are applied. Echoed back in every result. */
export interface NormalizedStackOptimizerRequest {
  workload: WorkloadSpec;
  minContextWindow: number | null;
  minMaxOutputTokens: number | null;
  visionRequired: boolean;
  toolCallingRequired: boolean;
  providers: string[];
  activeOnly: boolean;
  excludeModelIds: string[];
  excludeProviders: string[];
  priority: OptimizationPriority;
  limit: number | null;
  currency: string;
}

export type RequirementId =
  | "provider_allowed"
  | "provider_not_excluded"
  | "model_not_excluded"
  | "lifecycle_active"
  | "min_context_window"
  | "min_max_output_tokens"
  | "vision"
  | "tool_calling";

/**
 * `not_applicable` means the caller imposed no such constraint. `unknown`
 * means the constraint exists and the evidence to judge it does not — which
 * is a failure, not a pass.
 */
export type RequirementStatus =
  | "satisfied"
  | "unsatisfied"
  | "unknown"
  | "not_applicable";

export interface RequirementCheck {
  requirement: RequirementId;
  label: string;
  required: string | number | boolean | null;
  observed: string | number | boolean | null;
  status: RequirementStatus;
  /** Which evidence domain the observation came from, for provenance lookup. */
  domain: EvidenceDomain | null;
  detail: string;
}

/**
 * Why a cost component has no number. `not_applicable` is the honest answer
 * when the workload asks for zero tokens on that dimension: no price is
 * needed to know the cost is zero.
 */
export type CostComponentStatus = "calculated" | "not_priced" | "not_applicable";

export interface CostComponent {
  tokens: number;
  pricePer1MTokens: number | null;
  /** null whenever the component could not be computed from trusted evidence. */
  amount: number | null;
  status: CostComponentStatus;
  /** Reproducible arithmetic, e.g. "100000000 / 1000000 x 1.25 = 125". */
  formula: string;
}

export interface MonthlyCost {
  input: CostComponent;
  output: CostComponent;
  /** null unless both components resolved. Never a partial total. */
  totalMonthlyCost: number | null;
  currency: string | null;
  /** True when every component the workload needs was priced. */
  complete: boolean;
  pricingMode: string | null;
  contextTier: string | null;
  pricingSnapshotId: string | null;
  pricingObservedAt: string | null;
}

/** Why an otherwise eligible model could not enter the ranking. */
export type CostExclusionCode =
  | "no_pricing_evidence"
  | "input_price_unobserved"
  | "output_price_unobserved"
  | "currency_not_comparable";

export interface CostExclusion {
  code: CostExclusionCode;
  detail: string;
}

export interface OptimizerCandidate {
  canonicalModelId: string;
  modelName: string;
  displayName: string | null;
  provider: ModelProviderIdentity;
  cost: MonthlyCost;
  requirementChecks: RequirementCheck[];
  capabilities: {
    contextWindow: number | null;
    maxOutputTokens: number | null;
    supportsVision: boolean | null;
    supportsToolCalling: boolean | null;
  };
  lifecycleState: LifecycleState | null;
  endOfLife: boolean;
  freshness: ModelFreshness;
  provenance: Record<EvidenceDomain, ProvenanceView | null>;
  /** 1-based position in the ranking, or null when the model is not ranked. */
  rank: number | null;
  /** The metric the ranking compared, stated in words. */
  rankBasis: string | null;
  /** Set only for eligible models that carry no comparable price. */
  costExclusion: CostExclusion | null;
}

export interface ExcludedCandidate {
  canonicalModelId: string;
  modelName: string;
  provider: ModelProviderIdentity;
  /** Every failing check, in requirement order. Never just the first. */
  reasons: RequirementCheck[];
}

export interface OptimizerEvidenceFreshness {
  oldestObservedAt: string | null;
  newestObservedAt: string | null;
  /** Age of the oldest evidence backing a ranked candidate. */
  maxAgeMinutes: number | null;
}

/** Why the optimizer declined to name a winner. */
export interface InsufficientEvidence {
  code: "no_models" | "no_eligible_models" | "no_comparable_pricing";
  detail: string;
}

export interface StackOptimizerResult {
  request: NormalizedStackOptimizerRequest;
  generatedAt: string;
  totalModelsConsidered: number;
  eligibleCount: number;
  rankedCount: number;
  /** null whenever nothing could be ranked. A winner is never invented. */
  winner: OptimizerCandidate | null;
  ranked: OptimizerCandidate[];
  /** Met every requirement, but carries no comparable price. */
  eligibleWithoutCost: OptimizerCandidate[];
  excluded: ExcludedCandidate[];
  /** Deterministic, line by line: what was compared and why it ordered so. */
  explanation: string[];
  evidenceFreshness: OptimizerEvidenceFreshness;
  /** Deduplicated provenance for every ranked candidate's pricing evidence. */
  provenance: ProvenanceView[];
  insufficientEvidence: InsufficientEvidence | null;
}
