import type { TemporalEvidence } from "./contracts";

/**
 * Deterministic seeded demo evidence for the AI Radar hackathon demo.
 * 
 * Every record is explicitly isolated with `isDemo: true` and contains
 * complete provenance, source URLs, before/after values, and authority scores.
 */
export const DEMO_TEMPORAL_EVIDENCE: readonly TemporalEvidence[] = [
  // -------------------------------------------------------------------------
  // ANTHROPIC / CLAUDE (Hero provider timeline)
  // -------------------------------------------------------------------------
  {
    id: "demo-ant-001",
    provider: "anthropic",
    providerName: "Anthropic",
    model: "claude-3-5-sonnet-20241022",
    displayName: "Claude 3.5 Sonnet",
    changeType: "model_added",
    category: "catalog",
    field: null,
    pricingMode: "standard",
    contextTier: "default",
    previousValue: null,
    currentValue: "claude-3-5-sonnet-20241022",
    priceDelta: null,
    observedAt: "2026-08-10T14:30:00.000Z",
    source: {
      url: "https://www.anthropic.com/pricing",
      collectorId: "c_msx3bqlyjtv2qustx",
      kind: "pricing",
      label: "Anthropic official API pricing",
    },
    provenance: {
      runId: "demo-run-ant-01",
      externalRunId: "brightdata-snap-ant-801",
      currentSnapshotId: "demo-snap-ant-001",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 95,
    summary: "Claude 3.5 Sonnet (v2) launched at $3.00/1M input and $15.00/1M output tokens.",
    isDemo: true,
  },
  {
    id: "demo-ant-002",
    provider: "anthropic",
    providerName: "Anthropic",
    model: "claude-3-5-sonnet-20241022",
    displayName: "Claude 3.5 Sonnet",
    changeType: "price_decreased",
    category: "pricing",
    field: "cachedInputPricePer1MTokens",
    pricingMode: "standard",
    contextTier: "default",
    previousValue: 3.0,
    currentValue: 0.3,
    priceDelta: {
      previousPrice: 3.0,
      currentPrice: 0.3,
      absoluteChange: -2.7,
      percentChange: -90.0,
      unit: "USD per 1M tokens",
      field: "cachedInputPricePer1MTokens",
    },
    observedAt: "2026-08-11T09:15:00.000Z",
    source: {
      url: "https://www.anthropic.com/pricing",
      collectorId: "c_msx3bqlyjtv2qustx",
      kind: "pricing",
      label: "Anthropic official API pricing",
    },
    provenance: {
      runId: "demo-run-ant-02",
      externalRunId: "brightdata-snap-ant-802",
      previousSnapshotId: "demo-snap-ant-001",
      currentSnapshotId: "demo-snap-ant-002",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 92,
    summary: "Prompt caching enabled for Claude 3.5 Sonnet: cached input price dropped 90.0% ($3.00 → $0.30 / 1M tokens).",
    isDemo: true,
  },
  {
    id: "demo-ant-003",
    provider: "anthropic",
    providerName: "Anthropic",
    model: "claude-3-opus-20240229",
    displayName: "Claude 3 Opus",
    changeType: "deprecation_scheduled",
    category: "deprecations",
    field: "deprecatedDate",
    pricingMode: null,
    contextTier: null,
    previousValue: null,
    currentValue: "2026-08-01",
    priceDelta: null,
    observedAt: "2026-08-01T10:00:00.000Z",
    source: {
      url: "https://docs.anthropic.com/en/docs/resources/model-deprecations",
      collectorId: "c_msxj0fk3153bu9oz7l",
      kind: "models",
      label: "Anthropic model lifecycle and deprecations",
    },
    provenance: {
      runId: "demo-run-ant-03",
      externalRunId: "brightdata-snap-ant-803",
      currentLifecycleSnapshotId: "demo-lsnap-ant-003",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 85,
    summary: "Claude 3 Opus marked as deprecated on 2026-08-01 with migration advisory to Claude 3.5 Sonnet.",
    isDemo: true,
  },
  {
    id: "demo-ant-004",
    provider: "anthropic",
    providerName: "Anthropic",
    model: "claude-3-opus-20240229",
    displayName: "Claude 3 Opus",
    changeType: "retirement_not_before_scheduled",
    category: "retirements",
    field: "retirementNotBeforeDate",
    pricingMode: null,
    contextTier: null,
    previousValue: null,
    currentValue: "2027-01-05",
    priceDelta: null,
    observedAt: "2026-08-01T10:00:00.000Z",
    source: {
      url: "https://docs.anthropic.com/en/docs/resources/model-deprecations",
      collectorId: "c_msxj0fk3153bu9oz7l",
      kind: "models",
      label: "Anthropic model lifecycle and deprecations",
    },
    provenance: {
      runId: "demo-run-ant-03",
      externalRunId: "brightdata-snap-ant-803",
      currentLifecycleSnapshotId: "demo-lsnap-ant-003",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 80,
    summary: "Tentative retirement date published for Claude 3 Opus: Not sooner than 2027-01-05.",
    isDemo: true,
  },
  {
    id: "demo-ant-005",
    provider: "anthropic",
    providerName: "Anthropic",
    model: "claude-3-haiku-20240307",
    displayName: "Claude 3 Haiku",
    changeType: "price_decreased",
    category: "pricing",
    field: "cachedInputPricePer1MTokens",
    pricingMode: "standard",
    contextTier: "default",
    previousValue: 0.25,
    currentValue: 0.08,
    priceDelta: {
      previousPrice: 0.25,
      currentPrice: 0.08,
      absoluteChange: -0.17,
      percentChange: -68.0,
      unit: "USD per 1M tokens",
      field: "cachedInputPricePer1MTokens",
    },
    observedAt: "2026-08-05T16:20:00.000Z",
    source: {
      url: "https://www.anthropic.com/pricing",
      collectorId: "c_msx3bqlyjtv2qustx",
      kind: "pricing",
      label: "Anthropic official API pricing",
    },
    provenance: {
      runId: "demo-run-ant-04",
      externalRunId: "brightdata-snap-ant-804",
      previousSnapshotId: "demo-snap-ant-004",
      currentSnapshotId: "demo-snap-ant-005",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 78,
    summary: "Claude 3 Haiku cached input price reduced by 68.0% ($0.25 → $0.08 / 1M tokens).",
    isDemo: true,
  },
  {
    id: "demo-ant-006",
    provider: "anthropic",
    providerName: "Anthropic",
    model: "claude-2.1",
    displayName: "Claude 2.1",
    changeType: "lifecycle_transition",
    category: "lifecycle",
    field: "lifecycleState",
    pricingMode: null,
    contextTier: null,
    previousValue: "deprecated",
    currentValue: "retired",
    priceDelta: null,
    observedAt: "2026-07-28T00:00:00.000Z",
    source: {
      url: "https://docs.anthropic.com/en/docs/resources/model-deprecations",
      collectorId: "c_msxj0fk3153bu9oz7l",
      kind: "models",
      label: "Anthropic model lifecycle and deprecations",
    },
    provenance: {
      runId: "demo-run-ant-05",
      externalRunId: "brightdata-snap-ant-805",
      previousLifecycleSnapshotId: "demo-lsnap-ant-005",
      currentLifecycleSnapshotId: "demo-lsnap-ant-006",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 90,
    summary: "Claude 2.1 lifecycle transitioned to retired (API access shut down).",
    isDemo: true,
  },
  {
    id: "demo-ant-007",
    provider: "anthropic",
    providerName: "Anthropic",
    model: "claude-3-5-haiku-20241022",
    displayName: "Claude 3.5 Haiku",
    changeType: "model_added",
    category: "catalog",
    field: null,
    pricingMode: "standard",
    contextTier: "default",
    previousValue: null,
    currentValue: "claude-3-5-haiku-20241022",
    priceDelta: null,
    observedAt: "2026-08-14T11:00:00.000Z",
    source: {
      url: "https://www.anthropic.com/pricing",
      collectorId: "c_msx3bqlyjtv2qustx",
      kind: "pricing",
      label: "Anthropic official API pricing",
    },
    provenance: {
      runId: "demo-run-ant-06",
      externalRunId: "brightdata-snap-ant-806",
      currentSnapshotId: "demo-snap-ant-007",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 88,
    summary: "Claude 3.5 Haiku launched with standard pricing of $0.80/1M input and $4.00/1M output tokens.",
    isDemo: true,
  },

  // -------------------------------------------------------------------------
  // GOOGLE / GEMINI
  // -------------------------------------------------------------------------
  {
    id: "demo-gem-001",
    provider: "google",
    providerName: "Google",
    model: "gemini-1.5-pro-002",
    displayName: "Gemini 1.5 Pro-002",
    changeType: "price_decreased",
    category: "pricing",
    field: "inputPricePer1MTokens",
    pricingMode: "standard",
    contextTier: "default",
    previousValue: 3.5,
    currentValue: 1.25,
    priceDelta: {
      previousPrice: 3.5,
      currentPrice: 1.25,
      absoluteChange: -2.25,
      percentChange: -64.29,
      unit: "USD per 1M tokens",
      field: "inputPricePer1MTokens",
    },
    observedAt: "2026-08-08T18:00:00.000Z",
    source: {
      url: "https://ai.google.dev/pricing",
      collectorId: "c_msx3bqlyjtv2qustx",
      kind: "pricing",
      label: "Google AI Developer pricing",
    },
    provenance: {
      runId: "demo-run-gem-01",
      externalRunId: "brightdata-snap-gem-801",
      previousSnapshotId: "demo-snap-gem-001",
      currentSnapshotId: "demo-snap-gem-002",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 91,
    summary: "Gemini 1.5 Pro-002 input price reduced by 64.3% ($3.50 → $1.25 / 1M tokens).",
    isDemo: true,
  },
  {
    id: "demo-gem-002",
    provider: "google",
    providerName: "Google",
    model: "gemini-1.0-pro",
    displayName: "Gemini 1.0 Pro",
    changeType: "retirement_not_before_scheduled",
    category: "retirements",
    field: "retirementNotBeforeDate",
    pricingMode: null,
    contextTier: null,
    previousValue: null,
    currentValue: "2026-09-15",
    priceDelta: null,
    observedAt: "2026-08-03T12:00:00.000Z",
    source: {
      url: "https://ai.google.dev/gemini-api/docs/models/legacy",
      collectorId: "c_msxqpelk2cpxz8r386",
      kind: "models",
      label: "Google Gemini model lifecycle",
    },
    provenance: {
      runId: "demo-run-gem-02",
      externalRunId: "brightdata-snap-gem-802",
      currentLifecycleSnapshotId: "demo-lsnap-gem-002",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 84,
    summary: "Gemini 1.0 Pro shutdown scheduled not sooner than 2026-09-15.",
    isDemo: true,
  },
  {
    id: "demo-gem-003",
    provider: "google",
    providerName: "Google",
    model: "gemini-1.0-pro",
    displayName: "Gemini 1.0 Pro",
    changeType: "replacement_recommended",
    category: "replacements",
    field: "recommendedReplacement",
    pricingMode: null,
    contextTier: null,
    previousValue: null,
    currentValue: "gemini-1.5-flash",
    priceDelta: null,
    observedAt: "2026-08-03T12:00:00.000Z",
    source: {
      url: "https://ai.google.dev/gemini-api/docs/models/legacy",
      collectorId: "c_msxqpelk2cpxz8r386",
      kind: "models",
      label: "Google Gemini model lifecycle",
    },
    provenance: {
      runId: "demo-run-gem-02",
      externalRunId: "brightdata-snap-gem-802",
      currentLifecycleSnapshotId: "demo-lsnap-gem-002",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 82,
    summary: "Google officially recommended gemini-1.5-flash as the replacement for gemini-1.0-pro.",
    isDemo: true,
  },
  {
    id: "demo-gem-004",
    provider: "google",
    providerName: "Google",
    model: "gemini-1.5-flash-8b",
    displayName: "Gemini 1.5 Flash-8B",
    changeType: "model_added",
    category: "catalog",
    field: null,
    pricingMode: "standard",
    contextTier: "default",
    previousValue: null,
    currentValue: "gemini-1.5-flash-8b",
    priceDelta: null,
    observedAt: "2026-08-07T08:30:00.000Z",
    source: {
      url: "https://ai.google.dev/pricing",
      collectorId: "c_msx3bqlyjtv2qustx",
      kind: "pricing",
      label: "Google AI Developer pricing",
    },
    provenance: {
      runId: "demo-run-gem-03",
      externalRunId: "brightdata-snap-gem-803",
      currentSnapshotId: "demo-snap-gem-004",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 83,
    summary: "Gemini 1.5 Flash-8B added with ultra-low pricing of $0.0375/1M input tokens.",
    isDemo: true,
  },

  // -------------------------------------------------------------------------
  // OPENAI
  // -------------------------------------------------------------------------
  {
    id: "demo-oai-001",
    provider: "openai",
    providerName: "OpenAI",
    model: "gpt-4o",
    displayName: "GPT-4o",
    changeType: "price_decreased",
    category: "pricing",
    field: "inputPricePer1MTokens",
    pricingMode: "standard",
    contextTier: "default",
    previousValue: 5.0,
    currentValue: 2.5,
    priceDelta: {
      previousPrice: 5.0,
      currentPrice: 2.5,
      absoluteChange: -2.5,
      percentChange: -50.0,
      unit: "USD per 1M tokens",
      field: "inputPricePer1MTokens",
    },
    observedAt: "2026-08-06T20:00:00.000Z",
    source: {
      url: "https://openai.com/api/pricing/",
      collectorId: "c_msx3bqlyjtv2qustx",
      kind: "pricing",
      label: "OpenAI API pricing page",
    },
    provenance: {
      runId: "demo-run-oai-01",
      externalRunId: "brightdata-snap-oai-801",
      previousSnapshotId: "demo-snap-oai-001",
      currentSnapshotId: "demo-snap-oai-002",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 94,
    summary: "GPT-4o input pricing cut 50.0% ($5.00 → $2.50 / 1M tokens).",
    isDemo: true,
  },
  {
    id: "demo-oai-002",
    provider: "openai",
    providerName: "OpenAI",
    model: "gpt-4o",
    displayName: "GPT-4o",
    changeType: "price_decreased",
    category: "pricing",
    field: "outputPricePer1MTokens",
    pricingMode: "standard",
    contextTier: "default",
    previousValue: 15.0,
    currentValue: 10.0,
    priceDelta: {
      previousPrice: 15.0,
      currentPrice: 10.0,
      absoluteChange: -5.0,
      percentChange: -33.33,
      unit: "USD per 1M tokens",
      field: "outputPricePer1MTokens",
    },
    observedAt: "2026-08-06T20:00:00.000Z",
    source: {
      url: "https://openai.com/api/pricing/",
      collectorId: "c_msx3bqlyjtv2qustx",
      kind: "pricing",
      label: "OpenAI API pricing page",
    },
    provenance: {
      runId: "demo-run-oai-01",
      externalRunId: "brightdata-snap-oai-801",
      previousSnapshotId: "demo-snap-oai-001",
      currentSnapshotId: "demo-snap-oai-002",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 89,
    summary: "GPT-4o output pricing cut 33.3% ($15.00 → $10.00 / 1M tokens).",
    isDemo: true,
  },
  {
    id: "demo-oai-003",
    provider: "openai",
    providerName: "OpenAI",
    model: "gpt-4o-mini",
    displayName: "GPT-4o-mini",
    changeType: "model_added",
    category: "catalog",
    field: null,
    pricingMode: "standard",
    contextTier: "default",
    previousValue: null,
    currentValue: "gpt-4o-mini",
    priceDelta: null,
    observedAt: "2026-07-25T17:00:00.000Z",
    source: {
      url: "https://openai.com/api/pricing/",
      collectorId: "c_msx3bqlyjtv2qustx",
      kind: "pricing",
      label: "OpenAI API pricing page",
    },
    provenance: {
      runId: "demo-run-oai-02",
      externalRunId: "brightdata-snap-oai-802",
      currentSnapshotId: "demo-snap-oai-003",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 93,
    summary: "GPT-4o-mini launched at $0.15/1M input and $0.60/1M output tokens.",
    isDemo: true,
  },
  {
    id: "demo-oai-004",
    provider: "openai",
    providerName: "OpenAI",
    model: "gpt-3.5-turbo-0125",
    displayName: "GPT-3.5 Turbo (0125)",
    changeType: "deprecation_scheduled",
    category: "deprecations",
    field: "deprecatedDate",
    pricingMode: null,
    contextTier: null,
    previousValue: null,
    currentValue: "2026-08-01",
    priceDelta: null,
    observedAt: "2026-08-01T00:00:00.000Z",
    source: {
      url: "https://platform.openai.com/docs/deprecations",
      collectorId: "c_msxj0fk3153bu9oz7l",
      kind: "models",
      label: "OpenAI model deprecations",
    },
    provenance: {
      runId: "demo-run-oai-03",
      externalRunId: "brightdata-snap-oai-803",
      currentLifecycleSnapshotId: "demo-lsnap-oai-004",
    },
    authority: "authoritative",
    confidence: 1.0,
    significanceScore: 86,
    summary: "GPT-3.5 Turbo marked deprecated in favor of GPT-4o-mini.",
    isDemo: true,
  },

  // -------------------------------------------------------------------------
  // XAI
  // -------------------------------------------------------------------------
  {
    id: "demo-xai-001",
    provider: "xai",
    providerName: "xAI",
    model: "grok-2-1212",
    displayName: "Grok-2",
    changeType: "model_added",
    category: "catalog",
    field: null,
    pricingMode: "standard",
    contextTier: "default",
    previousValue: null,
    currentValue: "grok-2-1212",
    priceDelta: null,
    observedAt: "2026-08-12T22:00:00.000Z",
    source: {
      url: "https://x.ai/api",
      collectorId: "c_msx3bqlyjtv2qustx",
      kind: "pricing",
      label: "xAI official API docs",
    },
    provenance: {
      runId: "demo-run-xai-01",
      externalRunId: "brightdata-snap-xai-801",
      currentSnapshotId: "demo-snap-xai-001",
    },
    authority: "verified_scrape",
    confidence: 0.95,
    significanceScore: 87,
    summary: "Grok-2 added to catalog with standard pricing $2.00/1M input and $10.00/1M output tokens.",
    isDemo: true,
  },
  {
    id: "demo-xai-002",
    provider: "xai",
    providerName: "xAI",
    model: "grok-2-vision-1212",
    displayName: "Grok-2 Vision",
    changeType: "model_added",
    category: "catalog",
    field: null,
    pricingMode: "standard",
    contextTier: "default",
    previousValue: null,
    currentValue: "grok-2-vision-1212",
    priceDelta: null,
    observedAt: "2026-08-12T22:00:00.000Z",
    source: {
      url: "https://x.ai/api",
      collectorId: "c_msx3bqlyjtv2qustx",
      kind: "pricing",
      label: "xAI official API docs",
    },
    provenance: {
      runId: "demo-run-xai-01",
      externalRunId: "brightdata-snap-xai-801",
      currentSnapshotId: "demo-snap-xai-002",
    },
    authority: "verified_scrape",
    confidence: 0.95,
    significanceScore: 84,
    summary: "Grok-2 Vision added at $2.00/1M input and $10.00/1M output tokens.",
    isDemo: true,
  },
];

/**
 * Returns a cloned copy of demo temporal evidence filtered by a predicate.
 */
export function getDemoTemporalEvidence(
  filter?: (event: TemporalEvidence) => boolean,
): TemporalEvidence[] {
  const cloned = JSON.parse(JSON.stringify(DEMO_TEMPORAL_EVIDENCE)) as TemporalEvidence[];
  return filter ? cloned.filter(filter) : cloned;
}
