/**
 * Hand-maintained types for the AI Radar schema.
 *
 * Keep in sync with `supabase/migrations`. Once a project is linked you can
 * regenerate this file instead:
 *   npx supabase gen types typescript --linked > lib/supabase/types.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type SourceKind = "pricing" | "models" | "changelog" | "docs" | "other";

export type RunStatus = "running" | "succeeded" | "partial" | "failed";

export type ChangeType =
  | "model_added"
  | "model_removed"
  | "price_increased"
  | "price_decreased"
  | "metadata_changed"
  | "lifecycle_changed";

export type LifecycleState = "active" | "legacy" | "deprecated" | "retired";

export type RetirementNotBeforeObservation =
  | "unobserved"
  | "date"
  | "imprecise_date"
  | "explicitly_unannounced";

export type SentinelStatus =
  | "healthy"
  | "degraded"
  | "quarantined"
  | "healing"
  | "recovered"
  | "needs_review";

export type SentinelIncidentStatus =
  | "open"
  | "healing"
  | "resolved"
  | "dismissed"
  | "needs_review";

export type SentinelReasonCode =
  | "SCHEMA_VALIDATION_FAILURE"
  | "RECORD_COUNT_COLLAPSE"
  | "RECORD_COUNT_SPIKE"
  | "ZERO_RECORDS"
  | "DUPLICATE_IDENTIFIERS"
  | "ILLEGAL_ENUM_VALUE"
  | "ALL_PRICES_NULL"
  | "SEMANTIC_INVARIANT_VIOLATION"
  | "STALE_SOURCE"
  | "COLLECTOR_EXECUTION_FAILURE";

export type ProviderRow = {
  id: string;
  slug: string;
  name: string;
  homepage_url: string | null;
  created_at: string;
  updated_at: string;
};

export type SourceRow = {
  id: string;
  provider_id: string;
  kind: SourceKind;
  collector_id: string | null;
  source_url: string;
  label: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

export type ModelRow = {
  id: string;
  provider_id: string;
  model_name: string;
  display_name: string | null;
  metadata: Json;
  is_active: boolean;
  lifecycle_state: LifecycleState | null;
  deprecated_on: string | null;
  retirement_date: string | null;
  retirement_not_before_date: string | null;
  lifecycle_source_id: string | null;
  lifecycle_observed_at: string | null;
  first_seen_at: string;
  last_seen_at: string;
  created_at: string;
  updated_at: string;
};

export type CollectionRunRow = {
  id: string;
  source_id: string;
  status: RunStatus;
  external_run_id: string | null;
  triggered_by: string;
  started_at: string;
  completed_at: string | null;
  records_seen: number;
  records_accepted: number;
  records_rejected: number;
  error_message: string | null;
  error_details: Json | null;
  validation_errors: Json;
  created_at: string;
};

export type PricingSnapshotRow = {
  id: string;
  run_id: string;
  source_id: string;
  provider_id: string;
  model_id: string;
  pricing_mode: string;
  context_tier: string;
  input_price_per_1m_tokens: number | null;
  cached_input_price_per_1m_tokens: number | null;
  cache_write_price_per_1m_tokens: number | null;
  output_price_per_1m_tokens: number | null;
  currency: string;
  pricing_unit: string;
  source_url: string | null;
  extra: Json;
  raw: Json | null;
  observed_at: string;
  created_at: string;
  /** Generated by the database; never write to it. */
  content_hash: string;
};

export type ModelAliasRow = {
  id: string;
  provider_id: string;
  model_id: string;
  source_id: string | null;
  alias: string;
  alias_type: "api_model_id" | "source_name";
  first_seen_at: string;
  last_seen_at: string;
  created_at: string;
  updated_at: string;
};

export type LifecycleSnapshotRow = {
  id: string;
  run_id: string;
  source_id: string;
  provider_id: string;
  model_id: string;
  api_model_id: string;
  lifecycle_state: LifecycleState | null;
  deprecated_on: string | null;
  retirement_date: string | null;
  retirement_not_before_date: string | null;
  retirement_not_before_observation: RetirementNotBeforeObservation;
  recommended_replacement: string | null;
  recommended_replacement_model_id: string | null;
  recommended_replacement_observed: boolean;
  source_metadata: Json;
  source_url: string;
  raw: Json | null;
  observed_at: string;
  created_at: string;
  content_hash: string;
};

export type ChangeEventRow = {
  id: string;
  provider_id: string;
  source_id: string | null;
  run_id: string | null;
  model_id: string | null;
  change_type: ChangeType;
  field_name: string | null;
  /** Null for whole-model lifecycle events; set for tier-scoped changes. */
  pricing_mode: string | null;
  context_tier: string | null;
  old_value: Json | null;
  new_value: Json | null;
  previous_snapshot_id: string | null;
  current_snapshot_id: string | null;
  previous_lifecycle_snapshot_id: string | null;
  current_lifecycle_snapshot_id: string | null;
  summary: string | null;
  detected_at: string;
  created_at: string;
};

export type SentinelIncidentRow = {
  id: string;
  source_id: string;
  provider_id: string;
  run_id: string | null;
  status: SentinelIncidentStatus;
  severity: "info" | "warning" | "critical";
  reason_codes: SentinelReasonCode[];
  summary: string | null;
  records_seen: number;
  records_valid: number;
  records_invalid: number;
  expected_count: number | null;
  last_known_good_count: number | null;
  last_known_good_run_id: string | null;
  last_known_good_at: string | null;
  healing_attempt_count: number;
  resolution_note: string | null;
  created_at: string;
  updated_at: string;
  resolved_at: string | null;
};

export type SentinelQuarantinePayloadRow = {
  id: string;
  incident_id: string;
  source_id: string;
  run_id: string | null;
  raw_payload: Json;
  validation_errors: Json;
  created_at: string;
};

export type SentinelHealingAttemptRow = {
  id: string;
  incident_id: string;
  source_id: string;
  collector_id: string | null;
  attempt_number: number;
  prompt: string;
  status:
    | "initiated"
    | "in_progress"
    | "awaiting_approval"
    | "candidate_validated"
    | "candidate_rejected"
    | "approved"
    | "rejected"
    | "failed"
    | "timed_out";
  refactor_job_id: string | null;
  candidate_records_count: number | null;
  candidate_passed_validation: boolean | null;
  validation_details: Json | null;
  error_message: string | null;
  started_at: string;
  completed_at: string | null;
  created_at: string;
};

/** Row of the `latest_pricing_snapshots` view. */
export type LatestPricingSnapshotRow = PricingSnapshotRow & {
  model_name: string;
  provider_slug: string;
  provider_name: string;
};

export type LatestLifecycleSnapshotRow = LifecycleSnapshotRow & {
  model_name: string;
  projected_lifecycle_state: LifecycleState | null;
  provider_slug: string;
  provider_name: string;
};

/** Row of the `source_health` view. */
export type SourceHealthRow = {
  source_id: string;
  provider_id: string;
  kind: SourceKind;
  collector_id: string | null;
  source_url: string;
  is_active: boolean;
  last_run_id: string | null;
  last_run_status: RunStatus | null;
  last_run_started_at: string | null;
  last_run_completed_at: string | null;
  records_seen: number | null;
  records_accepted: number | null;
  records_rejected: number | null;
  error_message: string | null;
};

/** Row of the `sentinel_source_health` view. */
export type SentinelSourceHealthRow = {
  source_id: string;
  provider_id: string;
  provider_name: string;
  provider_slug: string;
  kind: SourceKind;
  collector_id: string | null;
  source_url: string;
  label: string | null;
  is_active: boolean;
  last_run_id: string | null;
  last_run_status: RunStatus | null;
  last_run_started_at: string | null;
  last_run_completed_at: string | null;
  last_run_records_seen: number | null;
  last_run_records_accepted: number | null;
  last_run_records_rejected: number | null;
  last_run_error_message: string | null;
  active_incident_id: string | null;
  active_incident_status: SentinelIncidentStatus | null;
  active_incident_severity: "info" | "warning" | "critical" | null;
  active_reason_codes: SentinelReasonCode[] | null;
  healing_attempt_count: number | null;
  last_known_good_count: number | null;
  last_known_good_at: string | null;
  sentinel_health_status: SentinelStatus;
};

/** Columns the database computes and refuses writes to. */
type ReadOnly = "content_hash";

/**
 * Insert shape: `Required` lists the NOT NULL columns without a default.
 * Everything else is optional because Postgres fills it in.
 */
type Insert<Row, Required extends keyof Row> = Pick<Row, Required> &
  Partial<Omit<Row, Required | Extract<keyof Row, ReadOnly>>>;

type Table<Row, Required extends keyof Row> = {
  Row: Row;
  Insert: Insert<Row, Required>;
  Update: Partial<Insert<Row, Required>>;
  Relationships: [];
};

type View<Row> = {
  Row: Row;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      providers: Table<ProviderRow, "slug" | "name">;
      sources: Table<SourceRow, "provider_id" | "source_url">;
      models: Table<ModelRow, "provider_id" | "model_name">;
      model_aliases: Table<
        ModelAliasRow,
        "provider_id" | "model_id" | "alias" | "alias_type"
      >;
      collection_runs: Table<CollectionRunRow, "source_id">;
      pricing_snapshots: Table<
        PricingSnapshotRow,
        "run_id" | "source_id" | "provider_id" | "model_id"
      >;
      lifecycle_snapshots: Table<
        LifecycleSnapshotRow,
        | "run_id"
        | "source_id"
        | "provider_id"
        | "model_id"
        | "api_model_id"
        | "source_url"
        | "observed_at"
      >;
      change_events: Table<ChangeEventRow, "provider_id" | "change_type">;
      sentinel_incidents: Table<SentinelIncidentRow, "source_id" | "provider_id">;
      sentinel_quarantine_payloads: Table<
        SentinelQuarantinePayloadRow,
        "incident_id" | "source_id"
      >;
      sentinel_healing_attempts: Table<
        SentinelHealingAttemptRow,
        "incident_id" | "source_id" | "prompt" | "status"
      >;
    };
    Views: {
      latest_pricing_snapshots: View<LatestPricingSnapshotRow>;
      latest_comparable_pricing_snapshots: View<LatestPricingSnapshotRow>;
      latest_lifecycle_snapshots: View<LatestLifecycleSnapshotRow>;
      latest_comparable_lifecycle_snapshots: View<LatestLifecycleSnapshotRow>;
      source_health: View<SourceHealthRow>;
      sentinel_source_health: View<SentinelSourceHealthRow>;
    };
    Functions: Record<never, never>;
    Enums: {
      source_kind: SourceKind;
      run_status: RunStatus;
      change_type: ChangeType;
      lifecycle_state: LifecycleState;
      sentinel_status: SentinelStatus;
      sentinel_incident_status: SentinelIncidentStatus;
    };
    CompositeTypes: Record<never, never>;
  };
};
